[package]
name = "threadcity"
version = "0.1.0"
edition = "2021"
default-run = "threadcity"

[dependencies]
mypthreads = { path = "../mypthreads" }
rand = "0.8"
rand_distr = "0.4"

[dev-dependencies]
mypthreads = { path = "../mypthreads" }
